image: maven:3-jdk-8

stages:
  - build
  
maven-build:
  stage: build
  script: "mvn package"
  artifacts:
    expose_as: 'JUnit Reports'
    paths:
      - target/surefire-reports/TEST-*.xml
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
